apiVersion: v1
kind: Service
metadata:
  name: homepage-dev-service
spec:
  selector:
    app: homepage-dev
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: homepageport
      nodePort: 30012
