apiVersion: v1
kind: Service
metadata:
  name: homepage-prod-service
spec:
  selector:
    app: homepage-prod
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: homepageport
      nodePort: 30013
